language: php

php: 
 - 5.6

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev

script:
 - php vendor/sensiolabs/security-checker/security-checker security:check composer.lock
 - vendor/bin/phpcs -n --standard=phpcsfunctions.xml src
 - vendor/bin/phpunit --coverage-clover=coverage.xml
 - vendor/bin/phpmd src text codesize,unusedcode,naming
 - vendor/bin/phpcs --standard=psr2 src
 - vendor/bin/phpcs -n --standard=phpcsdocblocks.xml src
 - vendor/bin/phploc src --progress
 - vendor/bin/phpcpd src

after_success:
 - bash <(curl -s https://codecov.io/bash)
